### PR TITLE
Add more roles and new channel resource

### PR DESCRIPTION
**Pull request by barrettclark**

### CODE REVIEW

**Comment by barrettclark** [comment]
@aequasi This is a clean PR with just my changes. The source files weren't `GoFmt` formatted, so the diffs are a lot bigger than the actual changes. I could break this into 2 commits to have the formatting be on it's own if you'd like.

**Comment by barrettclark** [comment]
Thank you :)

**Comment by barrettclark** [comment]
@aequasi Are you planning on deploying a new version of the provider to be able to take advantage of the changes?

**Comment by Xyaren** [comment]
I too would appreciate that.

**Pull request merged**
